"""
=============================================================================
BRIDGER HUB (BW) - ADVANCED STANDALONE BUNDLER
=============================================================================
Combines all 13 modular Luau files into a single, 100% self-contained
scripty_bundle.luau that can be uploaded to GitHub and loaded anywhere via:

    loadstring(game:HttpGet("https://raw.githubusercontent.com/<user>/<repo>/main/scripty_bundle.luau"))()

Architecture:
- Encapsulates each module inside an isolated closure:
    EMBEDDED_MODULES[name] = function(ctx) ... end
- Preserves module returns without terminating the main script.
- Uses the identical SHARED environment proxy and orchestrator as scripty.luau.
- Zero local file or network dependencies at runtime.
=============================================================================
"""

import os
import sys

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODULES_DIR = os.path.join(BASE_DIR, "modules")
SCRIPTY_PATH = os.path.join(BASE_DIR, "scripty.luau")
OUTPUT_PATH = os.path.join(BASE_DIR, "scripty_bundle.luau")
WORKSPACE_OUTPUT = r"C:\Users\noahh\AppData\Local\Real\workspace\BW\scripty_bundle.luau"

LOAD_ORDER = [
    "Core",
    "Utils",
    "Logging",
    "Config",
    "Movement",
    "Safety",
    "Fishing",
    "Automation",
    "Visuals",
    "Saint",
    "UI",
    "Combat",
    "Tabs",
]


def build_bundle():
    print("=" * 60)
    print("  BRIDGER HUB - ADVANCED BUNDLER")
    print("=" * 60)

    if not os.path.exists(SCRIPTY_PATH):
        sys.exit(f"Error: Main loader not found at {SCRIPTY_PATH}")

    with open(SCRIPTY_PATH, "r", encoding="utf-8") as f:
        scripty_src = f.read()

    loader_marker = "-- Module Loader"
    tail_marker = "local ctx = {"

    if loader_marker not in scripty_src or tail_marker not in scripty_src:
        sys.exit("Error: Could not locate loader markers in scripty.luau")

    header = scripty_src[: scripty_src.index(loader_marker)].strip()
    tail = scripty_src[scripty_src.index(tail_marker) :].strip()

    # Clean directive comments from header so they only appear once at the top
    clean_header_lines = [l for l in header.splitlines() if not l.strip().startswith("--!")]
    clean_header = "\n".join(clean_header_lines)

    bundle_parts = [
        "--!nocheck\n",
        "--!nolint\n",
        "-- ============================================================\n",
        "-- BRIDGER HUB (BW) - STANDALONE BUNDLED EDITION\n",
        "-- Self-contained single-file distribution for GitHub & Executors\n",
        "-- Generated by bundle.py - Zero external dependencies\n",
        "-- ============================================================\n\n",
        clean_header,
        "\n\n-- ============================================================\n",
        "-- EMBEDDED MODULE DEFINITIONS (Closure Encapsulation)\n",
        "-- ============================================================\n",
        "local EMBEDDED_MODULES = {}\n\n",
    ]

    total_lines = 0
    total_bytes = 0

    print(f"{'Module':<15} | {'Lines':>6} | {'Size':>10}")
    print("-" * 38)

    for mod_name in LOAD_ORDER:
        file_name = f"{mod_name}.luau"
        mod_path = os.path.join(MODULES_DIR, file_name)

        if not os.path.exists(mod_path):
            sys.exit(f"Error: Missing required module: {mod_path}")

        with open(mod_path, "r", encoding="utf-8") as f:
            src = f.read()

        lines = src.splitlines()
        clean_lines = []
        for line in lines:
            if line.strip() == "--!nocheck":
                continue
            clean_lines.append(line)

        clean_src = "\n".join(clean_lines)
        line_count = len(clean_lines)
        byte_count = len(clean_src.encode("utf-8"))

        total_lines += line_count
        total_bytes += byte_count

        print(f"{mod_name:<15} | {line_count:>6} | {byte_count:>8} B")

        bundle_parts.append(f"-- [[[ MODULE: {mod_name} ]]]\n")
        bundle_parts.append(f'EMBEDDED_MODULES["{mod_name}"] = function(...)\n')
        bundle_parts.append(clean_src)
        bundle_parts.append("\nend\n\n")

    print("-" * 38)
    print(f"{'TOTAL':<15} | {total_lines:>6} | {total_bytes:>8} B\n")

    embedded_loader = """-- ============================================================
-- STANDALONE MODULE LOADER
-- ============================================================
local function loadModule(name, ctx)
    local fn = EMBEDDED_MODULES[name]
    if not fn then
        error(string.format("[BW Bundle] Missing embedded module: %s", name))
    end
    setfenv(fn, setmetatable({}, {
        __index = SHARED,
        __newindex = SHARED
    }))
    local ok, res = pcall(fn, ctx)
    if not ok then
        error(string.format("[BW Bundle] Runtime error in %s: %s", name, tostring(res)))
    end
    if type(res) == "table" then
        for k, v in pairs(res) do
            SHARED[k] = v
        end
    end
    return res
end

"""

    bundle_parts.append(embedded_loader)
    bundle_parts.append(tail)
    bundle_parts.append("\n")

    bundled_code = "".join(bundle_parts)

    with open(OUTPUT_PATH, "w", encoding="utf-8") as out:
        out.write(bundled_code)

    print(f"Bundled successfully -> {OUTPUT_PATH}")
    print(f"Total bundle size: {len(bundled_code):,} chars, {len(bundled_code.splitlines()):,} lines")

    if os.path.exists(os.path.dirname(WORKSPACE_OUTPUT)):
        try:
            if os.path.exists(WORKSPACE_OUTPUT):
                os.remove(WORKSPACE_OUTPUT)
            os.link(OUTPUT_PATH, WORKSPACE_OUTPUT)
            print(f"Hardlinked to workspace -> {WORKSPACE_OUTPUT}")
        except Exception:
            import shutil

            shutil.copyfile(OUTPUT_PATH, WORKSPACE_OUTPUT)
            print(f"Copied to workspace -> {WORKSPACE_OUTPUT}")


if __name__ == "__main__":
    build_bundle()